version: "3.9"  # Docker Compose ファイルのバージョン

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container2
    ports:
      - "3306:3306"  # ホストの3306番ポートをコンテナの3306番ポートにマッピング
    environment:
      MYSQL_ROOT_PASSWORD: 1111  # MySQLのrootユーザーのパスワード
    volumes:
      - mysql-data:/var/lib/mysql  # データ永続化の設定
    restart: always  # 自動再起動設定

volumes:
  mysql-data:
